# Map of subgenres to more general supergenres
GENRE_MAPPING = {
    "ambient": set([
        "space ambient",
        "dark ambient",
        "ritual ambient",
        "tribal ambient",
        "easy listening",
        "chillout",
    ]),

    "blues": set([
        "piano blues",
        "alternative r&b",
        "contemporary r&b",
        "r&b",
        "doo-wop",
        "motown",
        "gospel",
    ]),

    "classical": set([
        "modern classical",
    ]),

    "country": set([
        "folk, world, & country", 
        "country rock",
        "dirty south",
    ]),

    "disco": set([
        "italo-disco",
        "euro-disco",
        "dark disco",
        "nu disco",
    ]),

    "electronic": set([
        "electronica",
        "electronic rock",
        "happy hardcore",
        "plunderphonics",
        "indietronica",
        "edm",
        "idm",
        "breaks",
        "synthwave",
        "eurodance",
        "drumstep",
        "power electronics",
        "drum and bass",
        "deep tech",
        "hardstyle",
        "electronicore",
        "big beat",
        "downtempo",
        "electro",
        "2-step",
        "eurobeat",
        "breakbeat",
        "chiptune",
        "dubstep",
        "trip hop",
        "future bass",
        "new wave",
        "bassline",
        "ebm",
        "french electro",
    ]),

    "funk": set([
        "funk metal",
        "funk rock",
        "funk / soul",
        "g-funk",
    ]),

    "folk": set([
        "folk rock",
        "folk punk",
        "folk metal",
        "folk, world, & country",
        "indie folk",
        "contemporary folk",
        "chamber folk",
        "dark folk",
        "pagan folk",
        "neofolk",
    ]),

    "hip hop": set([
        "hardcore hip hop",
        "alternative hip hop",
        "conscious hip hop",
        "east coast hip hop",
        "underground hip hop",
        "instrumental hip hop",
        "political hip hop",
        "west coast hip hop",
        "abstract hip hop",
        "southern hip hop",
        "experimental hip hop",
        "cloud rap",
        "rap metal",
        "pop rap",
        "rap rock",
        "gangsta rap",
        "jazz rap",
        "coke rap",
        "mafioso rap",
        "boom bap",
        "horrorcore",
        "leftfield",
    ]),

    "house": set([
        "acid house",
        "tech house",
        "deep house",
        "euro house",
        "hard house",
        "club",
        "electro house",
        "hands up",
        "french house",
        "stutter house",
        "progressive house",
        "garage house",
    ]),

    "jazz": set([
        "soul jazz",
        "dark jazz",
        "swing",
    ]),

    "indie": set([
        "indietronica",
        "indie pop",
        "indie folk",
        "shoegaze",
    ]),

    "metal": set([
        "death metal",
        "heavy metal",
        "crossover thrash",
        "thrash metal",
        "power metal",
        "funk metal",
        "glam metal",
        "groove metal",
        "progressive metal",
        "alternative metal",
        "nu metal",
        "rap metal",
        "symphonic metal",
        "folk metal",
        "viking metal",
        "speed metal",
        "metalcore",
    ]),

    "pop": set([
        "pop rock",
        "indie pop",
        "dance-pop",
        "pop rap",
        "chamber pop",
        "dream pop",
        "synth-pop",
        "pop soul",
        "art pop",
        "progressive pop",
        "bubblegum pop",
        "j-pop",
        "europop",
        "britpop",
        "electropop",
        "yé-yé",
        "power pop",
    ]),

    "punk": set([
        "punk rock",
        "folk punk",
        "post-punk",
        "post-punk revival",
        "dark wave",
    ]),

    "reggae": set([
        "dub",
        "ska",
        "dub techno",
    ]),

    "rock": set([
        "rock and roll",
        "folk rock",
        "indie rock",
        "pop rock",
        "alternative rock",
        "arena rock",
        "classic rock",
        "hard rock",
        "art rock",
        "acoustic rock",
        "glam",
        "geek rock",
        "soft rock",
        "rap rock",
        "grunge",
        "punk rock",
        "noise rock",
        "slacker rock",
        "funk rock",
        "electronic rock",
        "comedy rock",
        "psychedelic rock",
        "country rock",
        "power pop",
        "alternative pop",
        "noise pop",
        "shoegaze",
        "uk garage",
        "future garage",
        "garage house",
        "schlager",
        "aor",

    ]),

    "soul": set([
        "chipmunk soul",
        "psychedelic soul",
        "soul jazz",
        "pop soul",
        "funk / soul",
    ]),

    "stage & screen": set([
        "comedy",
        "musical",
        "music hall",
        "ballad",
        "orchestral",
    ]),

    "techno": set([
        "frenchcore",
        "minimal techno",
        "dub techno",
    ]),

    "trance": set([
        "psytrance",
        "vocal trance",
        "tech trance",
        "hard trance",
        "progressive trance",
        "psybient",
        "neo-psychedelia",
    ]),

    "world": set([
        "afrobeat",
        "afro house",
        "celtic",
        "chanson française",
        "latin",
        "uk garage",
        "britpop",
        "schlager",
        "euro house",
        "french house",
        "raï",
        "italo dance",
        "french electro",
        "frenchcore",
        "yé-yé",
        "exotica",
        "cumbia",
    ]),

    "other": set([
        "non-music",
        "instrumental",
        "singer-songwriter",
        "interview",
        "minimalism",
        "industrial",
        "experimental",
        "psychedelic",
        "noise",
        "dance",
        "lounge",
    ]),
}
